const functions = require('firebase-functions');
const cors = require('cors')({origin: true});
const express = require('express');
const count = require('./routes/count');
const {getMemos, addMemo} = require('./routes/database');
const app = express();
app.use(cors);
app.get('/count', count);
app.get('/memo', getMemos);
app.post('/memo', addMemo);
exports.api = functions.https.onRequest(app);
