version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
      
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-{{ .Branch }}-{{ checksum "hosting/package-lock.json" }}

      - run: 
          command: npm install 
          working_directory: hosting
      # run lint!
      - run: 
          command: npm run lint 
          working_directory: hosting
      - run: 
          command: npm run build 
          working_directory: hosting

      - save_cache:
          paths:
            - hosting/node_modules
          key: node-{{ .Branch }}-{{ checksum "hosting/package-lock.json" }}
        
      
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      # 
      #
      - run:
          command: npm install -g firebase-tools
      - run: 
          command: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN" 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
